# Generated by Django 5.1.3 on 2025-07-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('designation', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice-chairperson(technical)', 'Vice Chairperson (Technical)'), ('vice-chairperson(acting)', 'Vice Chairperson (Acting)'), ('general-secretary', 'General Secretary'), ('treasurer', 'Treasurer'), ('program-committee-chair', 'Program Committee Chair'), ('women-in-society', 'Women In Society'), ('member-development-coordinator', 'Member Development Coordinator'), ('technical-coordinator', 'Technical Coordinator'), ('publicity-coordinator', 'Publicity Coordinator'), ('department-representative(cse)', 'Department Representative (CSE)'), ('department-representative(eee)', 'Department Representative (EEE)'), ('department-representative(bba)', 'Department Representative (BBA)'), ('department-representative(pharmacy)', 'Department Representative (Pharmacy)')], max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Committee.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
