# Generated by Django 5.1.3 on 2025-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
