# Generated by Django 5.1.3 on 2025-07-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Committee', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin_link',
            new_name='linkedin_profile',
        ),
    ]
