# Generated by Django 5.1.3 on 2025-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Committee', '0006_rename_linkedin_link_userprofile_linkedin_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
