# Generated by Django 5.1.3 on 2025-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Committee', '0010_userprofile_gender_alter_userprofile_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.IntegerField(choices=[(1, 'Chairperson'), (2, 'Vice Chairperson (Activity)'), (3, 'Vice Chairperson (Technical)'), (4, 'General Secretary'), (5, 'Treasurer'), (6, 'Program Committee Chair'), (7, 'Women In Society'), (8, 'Member Development Coordinator'), (9, 'Technical Coordinator'), (10, 'Publicity Coordinator'), (11, 'Department Representative (CSE)'), (12, 'Department Representative (EEE)'), (13, 'Department Representative (BBA)'), (14, 'Department Representative (B.Pharm)')]),
        ),
    ]
